### ISSUE TITLE
Termux Error

### ISSUE THREAD

**Issue by Tax0787** [ShuchirJ/replit-cli#3]
tryit.

....
I hope this project isn't lie
because I fu** up my Holliday

**Comment by ShuchirJ** [comment]
Hey Tax0787,

Unfortunately because of the large amount of internal changes Replit has made since this project's release, Replit CLI is no longer functional.

**Comment by Tax0787** [comment]
OH, Sorry.
.....
I was too Emotional

It too bad that Replit CLI is die
I'm sorry...
